name: Dev Memes
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Update Dev Meme
    runs-on: ubuntu-latest
    steps:
      - name: Update meme
        uses: cgyinthehouse/dev-memes-for-README@v1.0
        with:
          fetch_num: 50
          commit_author: cgy
          commit_email: 100090733+cgyinthehouse@users.noreply.github.com
